# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "people"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthew Ericson"]
  s.date = "2013-03-06"
  s.email = "mericson@ericson.net"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "lib/people.rb",
    "people.gemspec",
    "test/people_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/mericson/people"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.0"
  s.summary = "Matts Name Parser"
end

